---
version: '3'
services:
  
  sonarr:
    container_name: sonarr
    image: lsioarmhf/sonarr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/g1/config/sonarr:/config
      - /mnt/g1/media/tv:/tv
      - /mnt/g1/downloads/complete:/downloads

  radarr:
    container_name: radarr
    image: lsioarmhf/radarr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 7878:7878
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/g1/config/radarr:/config
      - /mnt/g1/media/movies:/movies
      - /mnt/g1/downloads/complete:/downloads

  sabnzb:
    container_name: sabnzb
    image: lsioarmhf/sabnzb
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/g1/config/sabnzb:/config
      - /mnt/g1/downloads/complete:/downloads
      - /mnt/g1/downloads/incomplete:/incomplete-downloads

  plex:
    container_name: plex
    image: lsioarmhf/plex
    restart: unless-stopped
    network_mode: host
#    ports:
#      - 32400:32400
#      - 32400:32400/udp
#      - 32469:32469 
#      - 32469:32469/udp
#      - 5353:5353/udp
#      - 1900:1900/udp
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/g1/config/plex:/config
      - /mnt/g1/media/tv:/data/tvshows
      - /mnt/g1/media/movies:/data/movies
      - /mnt/g2/transcode:/transcode
