---
version: '3'
services:
  
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    deploy:
      placement:
        constraints:
          - node.labels.arc == arm
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
  sonarr:
    container_name: sonarr
    image: lsioarmhf/sonarr
    deploy:
      placement:
        constraints:
          - node.labels.arc == arm
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=sonarr.act.com
    volumes:
      - /mnt/g1/config/sonarr:/config
      - /mnt/g1/media/tv:/tv
      - /mnt/g1/downloads/complete:/downloads

  radarr:
    container_name: radarr
    image: lsioarmhf/radarr
    deploy:
      placement:
        constraints:
          - node.labels.arc == arm
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 7878:7878
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=radarr.act.com
    volumes:
      - /mnt/g1/config/radarr:/config
      - /mnt/g1/media/movies:/movies
      - /mnt/g1/downloads/complete:/downloads

  sabnzbd:
    container_name: sabnzbd
    image: lsioarmhf/sabnzbd
    deploy:
      placement:
        constraints:
          - node.labels.arc == arm
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=sab.act.com
      - VIRTUAL_PORT=8080
    volumes:
      - /mnt/g1/config/sabnzb:/config
      - /mnt/g1/downloads/complete:/downloads
      - /mnt/g1/downloads/incomplete:/incomplete-downloads

  plex:
    container_name: plex
    image: plexinc/pms-docker
    deploy:
      placement:
        constraints:
          - node.labels.arc == x64
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
      - ADVERTISE_IP=http://192.168.0.50:32400/
      - VIRTUAL_HOST=plex.act.com
      - VIRTUAL_PORT=32400
    hostname: PlexContainer
    volumes:
      - /mnt/g1/config/plex:/config
      - /mnt/g1/media:/data
      - /transcode:/transcode
