---
version: '2.1'
services:
  sonarr:
    container_name: sonarr
    image: lsioarmhf/sonarr
    restart: unless-stopped
    depends_on:
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/g1/config/sonarr:/config
      - /mnt/g1/media/tv:/tv
      - /mnt/g1/downloads/complete:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
    network_mode: host
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/g1/config/radarr:/config
      - /mnt/g1/media/movies:/movies
      - /mnt/g1/downloads/complete:/downloads
