---
version: '3'
services:
  plex-master:
    image: iamangus/arm-plexremotetranscoder2:master-latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
      - MASTER_IP="192.168.0.50"
    volumes:
      - /mnt/g1/config/plextest:/config
      - /mnt/g1/media/tv:/data/tvshows
      - /mnt/g1/media/movies:/data/movies

  plex-slave:
    image: deevus/plex-remote-transcoder:slave-latest
    #image: iamangus/arm-plexremotetranscoder2:slave-latest
    depends_on:
      - plex-master
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 2222:22
    environment:
      - TZ=america/chicago
      - PUID=1000
      - PGID=1000
      - MASTER_IP="192.168.0.50"
      - SLAVE_IP="192.168.0.50"
      - SLAVE_PORT="2222"
      - SLAVE_USER="plex"
    volumes:
      - /mnt/g1/config/plextest:/config
      - /mnt/g1/media/tv:/data/tvshows
      - /mnt/g1/media/movies:/data/movies
